channels:
- conda-forge
- bioconda
dependencies:
- python=3.7.6
- lammps=2020.03.03=py37_openmpi_2
- pyiron=0.2.13
- jupyter=1.0.0
- papermill=2.1.0
- scikit-learn=0.22.2
- nglview=2.7.5
- ovito=2.9.0
- mscorefonts=0.0.1
- snakemake=5.16.0
