channels:
- conda-forge
- bioconda
dependencies:
- python=3.7.3
- lammps=2019.06.05=py37_mpich_5
- pyiron=0.2.8
- jupyter=1.0.0
- papermill=1.1.0
- scikit-learn=0.21.3
- nglview=2.7.1
- ovito=2.9.0
- snakemake
- papermill
